export const tags = [
  "Body posture",
  "Nutrition tips",
  "Weight loss",
  "Weight gain",
  "Health status",
  "Arm/Shoulder fitness",
  "Nice shape",
  "Health improvement",
  "Body fit",
  "Motivation",
  "Weight watch",
  "Nutrition",
  "Physical fitness",
  "Leg fitness",
  "Fitness programs",
  "Intake Monitoring",
  "Others",
];
